global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'kong'
    static_configs:
      - targets: ['{IP:PORT TARGET']
    metrics_path: "/monitoring/metrics"
    basic_auth:
      username: 'metrics'
      password: 'metrics'
