apiVersion: v1
kind: Service
metadata:
  name: konga-svc
spec:
  type: LoadBalancer
  ports:
    - name: konga-proxy
      port: 80
      targetPort: 1337
      protocol: TCP
  selector:
    app: konga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga
          ports:
            - containerPort: 1337
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_HOST
              value: {HOST OR IP INSTANCE}
            - name: DB_USER
              value: {DATABASE USER}
            - name: DB_PASSWORD
              value: {DATABASE PASWORD}
            - name: DB_DATABASE
              value: {DATABASE NAME}
