version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./vol/nginx:/etc/nginx
      - ./ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
    restart: always
