version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: always
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=rm-d9j363az088f52b41zo.mysql.ap-southeast-5.rds.aliyuncs.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=antikode
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: always
    ports:
      - 8000:8080
    environment:
      - DB_SERVER_HOST=rm-d9j363az088f52b41zo.mysql.ap-southeast-5.rds.aliyuncs.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=antikode
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
